Fix double quotes leading to failure to load recipe
java.lang.Exception: while parsing a block mapping
 in 'reader', line 780, column 1:
    type: specs.openrewrite.org/v1be ...
    ^
expected <block end>, but found '<scalar>'
 in 'reader', line 782, column 36:
    displayName: "Require or disallow "Yoda" conditions "
                                       ^